services: 
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=Safety123!
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      
volumes:
  db:
    driver: local